# Site settings
title: Marks Polakovs
description: > # this means to ignore newlines until "baseurl:"
  The website of that guy.
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments

# comments
disqus: markspblog

# author info
# add your appropriate info here
author: Marks Polakovs
bio: Some guy.
email: marks@markspolakovs.me
email_md5: 8872af284590fc01257e47ec3b2a1000
twitter_username: SirMarksomnian
github_username: marksomnian

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'teal-500'
  navigation_color: 'pink-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
